# Generated by Django 5.2.9 on 2026-03-01 11:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('building_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], default='commercial', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=80, unique=True)),
                ('trigger_type', models.CharField(choices=[('smoke_sensor', 'Smoke Sensor'), ('heat_sensor', 'Heat Sensor'), ('manual', 'Manual'), ('periodic_scan', 'Periodic Scan')], max_length=20)),
                ('sensor_id', models.CharField(blank=True, default='', max_length=40)),
                ('trigger_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('acknowledged', 'Acknowledged'), ('false_alarm', 'False Alarm'), ('escalated', 'Escalated'), ('dispatched', 'Dispatched'), ('closed', 'Closed')], default='new', max_length=20)),
                ('fire_frames', models.PositiveIntegerField(default=0)),
                ('smoke_frames', models.PositiveIntegerField(default=0)),
                ('controlled_flame_frames', models.PositiveIntegerField(default=0)),
                ('total_frames', models.PositiveIntegerField(default=0)),
                ('fire_persistence', models.FloatField(default=0.0)),
                ('max_fire_conf', models.FloatField(default=0.0)),
                ('mean_fire_conf', models.FloatField(default=0.0)),
                ('fire_bbox_area_growth_rate', models.FloatField(default=0.0)),
                ('smoke_conf_trend', models.CharField(blank=True, default='stable', max_length=20)),
                ('scenario', models.CharField(blank=True, default='', max_length=50)),
                ('advisory_risk_level', models.CharField(blank=True, default='', max_length=10)),
                ('advisory_threat_score', models.FloatField(default=0.0)),
                ('advisory_confidence', models.FloatField(default=0.0)),
                ('final_risk_score', models.FloatField(default=0.0)),
                ('decision', models.CharField(blank=True, default='monitor', max_length=40)),
                ('keyframe_path', models.CharField(blank=True, default='', max_length=255)),
                ('annotated_frame_path', models.CharField(blank=True, default='', max_length=255)),
                ('explainability_json', models.JSONField(blank=True, default=list)),
                ('score_breakdown_json', models.JSONField(blank=True, default=dict)),
                ('response_packet_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=60, unique=True)),
                ('w1_yolo_detection_strength', models.FloatField(default=0.35)),
                ('w2_fire_persistence', models.FloatField(default=0.2)),
                ('w3_smoke_presence', models.FloatField(default=0.15)),
                ('w4_growth_rate', models.FloatField(default=0.1)),
                ('w5_context_modifier', models.FloatField(default=0.1)),
                ('w6_openai_threat_score', models.FloatField(default=0.1)),
                ('medium_threshold', models.FloatField(default=0.55)),
                ('high_threshold', models.FloatField(default=0.8)),
            ],
        ),
        migrations.CreateModel(
            name='EventAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ack', 'ACK'), ('false_alarm', 'FALSE ALARM'), ('escalate', 'ESCALATE')], max_length=20)),
                ('actor', models.CharField(blank=True, default='dashboard_user', max_length=60)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='firewatch.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('floor_level', models.CharField(blank=True, default='', max_length=20)),
                ('location_type', models.CharField(choices=[('corridor', 'Corridor'), ('pantry', 'Pantry'), ('carpark', 'Carpark'), ('stage', 'Stage'), ('warehouse', 'Warehouse'), ('kitchen', 'Kitchen'), ('other', 'Other')], default='other', max_length=20)),
                ('known_cooking_zone', models.BooleanField(default=False)),
                ('floorplan_x', models.FloatField(default=0.5)),
                ('floorplan_y', models.FloatField(default=0.5)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='firewatch.building')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='firewatch.zone'),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=40, unique=True)),
                ('rtsp_url', models.CharField(blank=True, default='', max_length=500)),
                ('default_fps', models.PositiveIntegerField(default=10)),
                ('active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='firewatch.zone')),
            ],
        ),
        migrations.CreateModel(
            name='FrameDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_index', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('detections_json', models.JSONField(default=list)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frame_detections', to='firewatch.camera')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_detections', to='firewatch.event')),
            ],
            options={
                'ordering': ['frame_index'],
                'indexes': [models.Index(fields=['event', 'camera', 'frame_index'], name='firewatch_f_event_i_975758_idx')],
            },
        ),
    ]
