# Generated by Django 5.2.9 on 2026-03-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveIntegerField(default=20)),
                ('cols', models.PositiveIntegerField(default=20)),
                ('cells_json', models.JSONField(blank=True, default=list)),
                ('camera_points_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='firewatch.zone')),
            ],
        ),
    ]
