# Generated by Django 5.2.9 on 2026-03-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewatch', '0002_zonelayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='authority_notifications_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='flow_validation_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='risk_action',
            field=models.CharField(blank=True, default='log_watch', max_length=80),
        ),
        migrations.AddField(
            model_name='event',
            name='risk_level',
            field=models.CharField(blank=True, default='no_fire_risk', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='stage_outputs_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
