# Generated by Django 5.2.9 on 2026-03-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewatch', '0003_event_authority_notifications_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='classification_runs_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='emergency_call_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='emergency_call_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='emergency_call_status',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='event',
            name='first_emergency_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='first_hazard_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
